### ISSUE TITLE
Improve accessibility of AnchorJS links

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/anchorjs#12]
In https://github.com/bryanbraun/anchorjs/issues/10, @XhmikosR proposed this:

> We should specify aria-hidden="true" for the icon-link span. Or even better, add a title in the a tag.

This issue is for discussing this or other approaches to improve accessibility of AnchorJS links.

**Comment by bryanbraun** [comment]
I inspected Github's deep links (the ones they use for heading in rendered README.md files) to see how they handle it, and this is what I saw:

```html
<a id="user-content-poor-mans-styleguide" class="anchor" href="#poor-mans-styleguide" aria-hidden="true">
    <span class="octicon octicon-link"></span>
</a>
```

They put `aria-hidden` on the `<a>`, which is a bit confusing to me. In principle, I don't like to provide functionality for sighted users and hide it for non-sighted. I'm thinking of putting it on the empty span instead.

I did some research about the title attribute, and learned some things I didn't know:
* http://www.paciellogroup.com/blog/2012/01/html5-accessibility-chops-title-attribute-use-and-abuse/
* http://blog.silktide.com/2013/01/i-thought-title-text-improved-accessibility-i-was-wrong/

In short, using title for accessibility is, at best, ineffective. That second article proposes avoiding the title and keeping advisory text for non-sighted users off screen in a span tag. In our case that might look something like this:

### Proposed approach:

```html
<a class="anchorjs-link" href="#' + elementID + '">
    <span class="anchorjs-description">Anchor link for:' + roughText + '</span>
    <span class="anchorjs-icon" aria-hidden="true"></span>
</a>
```
```css
/* Hide only visually, but have it available for screenreaders: h5bp.com/v */
.anchorjs-description {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
}
```

The `roughText` variable is already available in the script (it was used for creating IDs).

Anybody have opinions on that approach?
