### ISSUE TITLE
Arrow demo broken in some cases

### ISSUE THREAD

**Issue by XhmikosR** [bryanbraun/anchorjs#131]
On my main OS with Windows 10 and Firefox 71.0.0, using a DPI of 175%, the arrow example is broken:

![Screenshot_2019-12-07 AnchorJS - Add deep anchor links to your docs](https://user-images.githubusercontent.com/349621/70376772-30aeef80-1915-11ea-889d-458ace874786.png)

It's a tricky issue to solve :/ Using

```css
.hover-examples .example:nth-child(4) .anchorjs-link::before {
  border: 1.135rem solid #fff;
}
```

fixes the issue on Firefox but then breaks on Chrome on my machine.

Not super important I guess but I thought I'd mention it.
