### ISSUE TITLE
Force icon size?

### ISSUE THREAD

**Issue by jkauffman503** [bryanbraun/anchorjs#57]
Currently, the anchor icon gets resized based on the tag (or font size, I'm not sure). Is there a way to force the icon size to be consistent for all tags added? For example, I want to use the H1-sized icon for my h2, h3, h4, h5, and h6 tags.

**Comment by bryanbraun** [comment]
Yeah you can do that. The default icon comes from an icon-font, so the size is based on the `font-size` property. Usually the icon's `font-size` is inherited from the heading, but you can set it directly, with a CSS rule like this one:

```css

/* make all anchorjs links the same size... 32px */
.anchorjs-link {
  font-size: 32px;
}
```

This would also work if you used one of the unicode icons (like `#`, `¶`, `❡`, or `§`).
